repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0  # Use a versão específica do Flake8
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 23.3.0  # Use a versão específica do Black
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Use a versão específica do isort
    hooks:
      - id: isort
